/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:829dd391-2264-447a-ab0e-b54acd4acada",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_7WFVse68s",
    "aws_user_pools_web_client_id": "11jck81hehtgj7ufu892uh203p",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ct6uvuno4rgkxcp5qlz3o7wloy.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
